version: 0.2
phases:
  install:
    runtime-versions:
      python: 3.11
    commands:
      - echo "No dependencies to install............."
  build:
    commands:
      - echo "Adding lambda function to the deployment_package_doordash.zip................"
      - zip -g deployment_package_doordash.zip doordash_lambda.py
  post_build:
    commands:
      - echo "Uploading to s3................."
      - aws s3 cp deployment_package_doordash.zip s3://s3-aws-de-cicd/
      - echo "Creating lambda function via s3.............."
      - aws lambda update-function-code --function-name aws-de-1-doordash --s3-bucket s3-aws-de-cicd --s3-key deployment_package_doordash.zip
      - aws lambda wait function-updated --function-name aws-de-1-doordash
      - aws lambda update-function-configuration --function-name aws-de-1-doordash --handler doordash_lambda.lambda_handler
      - echo "Deployment complete !.............."
